//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV.App_LocalResources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОПИСАНИЕ.
        /// </summary>
        public static string AboutPageLabel {
            get {
                return ResourceManager.GetString("AboutPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      
        /// XXXТакже имеется информация о следующих навыках данного экземпляра:xxx
        ///
        /// XXXРасширенные границы эрудицииxxx
        ///Помимо записанных в ПЗУ данных о разработке,имеется большое количество информации и общих знаний в самых разных направлениях: от ботаники до астрономии. Данное улучшение позволяет новой версии решать задачи самого разного направления без привлечения дополнительных ресурсов и специалистов.
        ///
        /// XXXВстроенный модуль самообученияxxx
        ///При наблюдении за моделями предыдущего поколения, был выяв [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdditionalSkills {
            get {
                return ResourceManager.GetString("AdditionalSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возраст.
        /// </summary>
        public static string AgeLabel {
            get {
                return ResourceManager.GetString("AgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание всем агентам. 
        ///
        ///От матрицы был отключен эксперементальный образец разработчика ПО нового поколения 
        ///&quot;.Net Developer 3000&quot;. 
        ///
        ///Он не вооружен, но изобретателен, непредсказуем и потому чрезвычайно опасен.
        ///
        ///Основная информация доступна сейчас на вашей консоли. 
        ///
        ///Для более детальной информации перейдите по ссылке:.
        /// </summary>
        public static string AttentionText {
            get {
                return ResourceManager.GetString("AttentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ИНФОРМАЦИЯ.
        /// </summary>
        public static string BasicInfoTitle {
            get {
                return ResourceManager.GetString("BasicInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город.
        /// </summary>
        public static string CityLabel {
            get {
                return ResourceManager.GetString("CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КОНТАКТЫ.
        /// </summary>
        public static string ContactsPageLabel {
            get {
                return ResourceManager.GetString("ContactsPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна.
        /// </summary>
        public static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalLogic.
        /// </summary>
        public static string CurrentCompany {
            get {
                return ResourceManager.GetString("CurrentCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.globallogic.com/ua/.
        /// </summary>
        public static string CurrentCompanyLink {
            get {
                return ResourceManager.GetString("CurrentCompanyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РЕЗЮМЕ.
        /// </summary>
        public static string CVPageLabel {
            get {
                return ResourceManager.GetString("CVPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать резюме.
        /// </summary>
        public static string DownloadCV {
            get {
                return ResourceManager.GetString("DownloadCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опыт.
        /// </summary>
        public static string ExperienceLabel {
            get {
                return ResourceManager.GetString("ExperienceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГЛАВНАЯ.
        /// </summary>
        public static string HomePageLabel {
            get {
                return ResourceManager.GetString("HomePageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Киев.
        /// </summary>
        public static string Kyiv {
            get {
                return ResourceManager.GetString("Kyiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень.
        /// </summary>
        public static string LevelLabel {
            get {
                return ResourceManager.GetString("LevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Где искать.
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// XXXОпыт, накопленный за время обучения и работы включает следующие навыки:xxx
        ///- разработка веб-приложений и сервисов на платформе .Net, .Net Core
        ///- разработка десктоп-приложений: WinForms, WPF, WCF
        ///- разработка БД в средах MS Sql, Oracle
        ///- работа с БД из .Net приложений (ORM-Lite, Entity Framework, CQRS, ADO.Net)
        ///- создание веб страниц, с использованием HTML, CSS, JS, JQuery, Dart, Angular
        ///- разработка и интеграция с системами SalesForce, SAP, Pace и тд.
        /// </summary>
        public static string MainSkills {
            get {
                return ResourceManager.GetString("MainSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужской.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синьор.
        /// </summary>
        public static string Middle {
            get {
                return ResourceManager.GetString("Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.
        /// </summary>
        public static string MonthsLabel {
            get {
                return ResourceManager.GetString("MonthsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дмитрий Стребуль.
        /// </summary>
        public static string MyName {
            get {
                return ResourceManager.GetString("MyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Разработчик.
        /// </summary>
        public static string MySpec {
            get {
                return ResourceManager.GetString("MySpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        public static string nextPageLabel {
            get {
                return ResourceManager.GetString("nextPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тел..
        /// </summary>
        public static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deadik@gmail.com.
        /// </summary>
        public static string RealEmail {
            get {
                return ResourceManager.GetString("RealEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0737899987.
        /// </summary>
        public static string RealPhone {
            get {
                return ResourceManager.GetString("RealPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dimadod.
        /// </summary>
        public static string RealSkype {
            get {
                return ResourceManager.GetString("RealSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://vk.com/dima_strebul.
        /// </summary>
        public static string RealVK {
            get {
                return ResourceManager.GetString("RealVK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string SexLabel {
            get {
                return ResourceManager.GetString("SexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string Skype {
            get {
                return ResourceManager.GetString("Skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направление.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Украина.
        /// </summary>
        public static string Ukraine {
            get {
                return ResourceManager.GetString("Ukraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viber.
        /// </summary>
        public static string Viber {
            get {
                return ResourceManager.GetString("Viber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВК.
        /// </summary>
        public static string VKLabel {
            get {
                return ResourceManager.GetString("VKLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to г.
        /// </summary>
        public static string YearsLabel {
            get {
                return ResourceManager.GetString("YearsLabel", resourceCulture);
            }
        }
    }
}
