//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CV.App_LocalResources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возраст.
        /// </summary>
        public static string AgeLabel {
            get {
                return ResourceManager.GetString("AgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание всем агентам. 
        ///
        ///От матрицы был отключен эксперементальный образец разработчика нового поколения &quot;.Net developer 3000&quot;. 
        ///
        ///Он не вооружен, но изобретателен, непредсказуем и потому чрезвычайно опасен.
        ///
        ///Основная информация доступна сейчас на вашей консоли. 
        ///
        ///Для более детальной информации перейдите по ссылке:.
        /// </summary>
        public static string AttentionText {
            get {
                return ResourceManager.GetString("AttentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основная информация.
        /// </summary>
        public static string BasicInfoTitle {
            get {
                return ResourceManager.GetString("BasicInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город.
        /// </summary>
        public static string CityLabel {
            get {
                return ResourceManager.GetString("CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна.
        /// </summary>
        public static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GlobalLogic.
        /// </summary>
        public static string CurrentCompany {
            get {
                return ResourceManager.GetString("CurrentCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://www.globallogic.com/ua/.
        /// </summary>
        public static string CurrentCompanyLink {
            get {
                return ResourceManager.GetString("CurrentCompanyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опыт.
        /// </summary>
        public static string ExperienceLabel {
            get {
                return ResourceManager.GetString("ExperienceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Киев.
        /// </summary>
        public static string Kyiv {
            get {
                return ResourceManager.GetString("Kyiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень.
        /// </summary>
        public static string LevelLabel {
            get {
                return ResourceManager.GetString("LevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предположительное
        ///местоположение.
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мужской.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний.
        /// </summary>
        public static string Middle {
            get {
                return ResourceManager.GetString("Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на м.
        /// </summary>
        public static string MonthsLabel {
            get {
                return ResourceManager.GetString("MonthsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить.
        /// </summary>
        public static string nextPageLabel {
            get {
                return ResourceManager.GetString("nextPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пол.
        /// </summary>
        public static string SexLabel {
            get {
                return ResourceManager.GetString("SexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Украина.
        /// </summary>
        public static string Ukraine {
            get {
                return ResourceManager.GetString("Ukraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на г.
        /// </summary>
        public static string YearsLabel {
            get {
                return ResourceManager.GetString("YearsLabel", resourceCulture);
            }
        }
    }
}
